
trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
  - job: deploy_job
    displayName: terraform job
    steps:
    - task: TerraformInstaller@1
      displayName: terraform install
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceAWS: 'awsserviceconnection'
        backendAWSBucketName: 'saravananterraformstate'
        backendAWSKey: 'terraform.state'
    - task: TerraformTaskV4@4
      displayName: terraform apply
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAWS: 'awsserviceconnection'