trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
  - job: deploy_job
    displayName: terraform job
    steps:
    - script: |
       echo "Cleaning up existing Terraform installations..."
       rm -rf /opt/hostedtoolcache/terraform
      displayName: Clean Terraform Cache
    - task: TerraformInstaller@1
      displayName: terraform install
      inputs:
        terraformVersion: 'latest'
    - script: terraform version
      displayName: Verify Terraform Installation
    - task: TerraformTaskV4@4
      displayName: terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
        backendServiceAWS: 'awsserviceconnection'
        backendAWSBucketName: 'terraform'
        backendAWSKey: 'terraform.tfstate'
    - task: TerraformTaskV4@4
      displayName: terraform apply
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/aws'
        environmentServiceNameAWS: 'awsserviceconnection'
